language: java

jdk:
  - openjdk8

sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  - ./install-thrift-0.9.3.sh

install:
  - ./gradlew spotlessCheck
  - ./gradlew assemble

script:
  - ./gradlew check
